name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if build exists
        run: |
          echo "Checking if build exists..."
          if [ ! -d "dist" ]; then
            echo "Build does not exist. Skipping deployment."
            exit 0
          fi
          echo "Build exists. Proceeding with deployment."
  deploy:
    runs-on: ubuntu-latest
    needs:
      - check-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          folder: dist
